rules:
  - name: "block-go-test"
    pattern: "go test.*"
    action: "deny"
    message: "Use make test instead for better TDD integration"
    alternatives:
      - "make test          # Run all tests"
      - "make test-unit     # Run unit tests only"
    use_claude: false

  - name: "dangerous-rm"
    pattern: "rm -rf /.*"
    action: "deny"
    message: "⚠️  Dangerous rm command detected"
    alternatives:
      - "Be more specific with your rm command"
      - "Use a safer alternative like moving to trash"
    use_claude: true
    claude_prompt: "Explain why this rm command is dangerous and suggest safer alternatives"