# Claude Binary Configuration (optional)
# By default, Bumpers automatically detects Claude in these locations:
#   1. ~/.claude/local/claude (local installation)
#   2. claude in PATH (system installation)  
#   3. /opt/homebrew/bin/claude (macOS Homebrew)
#   4. /usr/local/bin/claude (Unix standard)
# Uncomment and specify a custom path if needed:
# claude_binary: "/path/to/your/claude"

rules:
  - name: "block-go-test"
    pattern: "go test.*"
    action: "deny"
    message: "Use make test instead for better TDD integration"
    alternatives:
      - "make test          # Run all tests"
      - "make test-unit     # Run unit tests only"
    use_claude: false

  - name: "dangerous-rm"
    pattern: "rm -rf /.*"
    action: "deny"
    message: "⚠️  Dangerous rm command detected"
    alternatives:
      - "Be more specific with your rm command"
      - "Use a safer alternative like moving to trash"
    use_claude: true
    claude_prompt: "Explain why this rm command is dangerous and suggest safer alternatives"