# Bumpers Configuration
# This file defines rules for command guarding in Claude Code

# Claude Binary Configuration (optional)
# By default, Bumpers automatically detects Claude in these locations:
#   1. ~/.claude/local/claude (local installation)
#   2. claude in PATH (system installation)  
#   3. /opt/homebrew/bin/claude (macOS Homebrew)
#   4. /usr/local/bin/claude (Unix standard)
# Uncomment and specify a custom path if needed:
# claude_binary: "/path/to/your/claude"

rules:
  - pattern: "go test"
    response: |
      Use make test instead for better TDD integration
      
      Try one of these alternatives:
      - make test          # Run all tests
      - make test-unit     # Run unit tests only

  - pattern: "rm -rf /*"
    response: |
      ⚠️  Dangerous rm command detected
      
      This command could delete important system files!
      
      Safer alternatives:
      - Be more specific with your rm command
      - Use safer alternatives like moving to trash
      - Double-check the path before using -rf flags
    use_claude: true
    prompt: "Explain why this rm command is dangerous and suggest safer alternatives"